name: Compile
on:
  pull_request:
    branches: [ "main","develop"]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: zerasul/durangodevkit:latest
      env:
        RESCOMP: /durango/rescomp/rescomp.jar
      volumes:
        - /durangolib:/src/durango
      options: --cpus 1
    steps:
      - uses: actions/checkout@v3
      - name: Compile Lib
        run: git config --global --add safe.directory /__w/DurangoLib/DurangoLib && make
